# alternative dagmodel with no income distr and 
#

g <- graphLayout(dagitty('dag {
AGE_AVG [pos="-2.280,-0.022"]
ENERGY_AVG [pos="-0.240,-0.068"]
HH_SIZE [pos="-0.631,-0.043"]
HOUSE_VAL_AVG [pos="-1.027,-0.052"]
INCOME_AVG [pos="0.799,-0.061"]
BIRTH_REL [pos="-1.503,-0.027"]
BUSINESS_REL [pos="-0.842,-0.064"]
CAR_PER_HH [pos="0.892,-0.076"]
CRIME_TOTAL [outcome,pos="1.255,-0.023"]
VACANCY [pos="-0.099,-0.053"]
PUB_SERV [pos="-0.090,-0.080"]
LAND_SIZE [pos="-2.302,-0.065"]
MARRIED_PCT [pos="-0.775,-0.027"]
MORTALITY_REL [pos="-1.694,-0.023"]
FEMALE_PCT [pos="-1.256,-0.035"]
PERC_SOCSEC [pos="1.339,-0.063"]
POPULATION [exposure,pos="-2.104,-0.042"]
DENS_POP [pos="-1.339,-0.066"]
AGE_AVG -> MORTALITY_REL
AGE_AVG -> POPULATION
ENERGY_AVG -> CRIME_TOTAL
HH_SIZE -> ENERGY_AVG
HH_SIZE -> HOUSE_VAL_AVG
INCOME_AVG -> CRIME_TOTAL
INCOME_AVG -> PERC_SOCSEC
INCOME_AVG <-> CAR_PER_HH
BIRTH_REL -> POPULATION
BUSINESS_REL -> HOUSE_VAL_AVG
CAR_PER_HH -> PUB_SERV
CAR_PER_HH -> PERC_SOCSEC
VACANCY -> ENERGY_AVG
VACANCY -> HH_SIZE
VACANCY -> CRIME_TOTAL
PUB_SERV -> CRIME_TOTAL
LAND_SIZE -> POPULATION
LAND_SIZE -> DENS_POP
MARRIED_PCT -> CRIME_TOTAL
MORTALITY_REL -> POPULATION
FEMALE_PCT -> CRIME_TOTAL
PERC_SOCSEC -> CRIME_TOTAL
POPULATION -> FEMALE_PCT
POPULATION -> DENS_POP
DENS_POP -> HOUSE_VAL_AVG
DENS_POP -> BUSINESS_REL
DENS_POP -> PUB_SERV
}
'))
plot(g)

d <- subset(cbsData, select = c(
AGE_AVG,
ENERGY_AVG,
HH_SIZE,
HOUSE_VAL_AVG,
INCOME_AVG,
BIRTH_REL,
BUSINESS_REL,
CAR_PER_HH,
CRIME_TOTAL,
VACANCY,
PUB_SERV,
LAND_SIZE,
MARRIED_PCT,
MORTALITY_REL,
FEMALE_PCT,
SOCSEC_PCT,
POPULATION,
DENS_POP ) )

# localTests(g,d,type = 'cis.chisq')
