# alternative dagmodel with no income distr and 
#

g <- graphLayout(dagitty('dag {
AVG_AGE [pos="-2.280,-0.022"]
AVG_ENERGY_CONS [pos="-0.240,-0.068"]
AVG_HH_SIZE [pos="-0.631,-0.043"]
AVG_HOUSE_VALUE [pos="-1.027,-0.052"]
AVG_INCOME_CAPITA [pos="0.799,-0.061"]
BIRTH_REL [pos="-1.503,-0.027"]
BUSINESS_LOCATIONS [pos="-0.842,-0.064"]
CAR_PER_HH [pos="0.892,-0.076"]
CRIME_TOTAL [outcome,pos="1.255,-0.023"]
EMPTY_HOUSE_PERC [pos="-0.099,-0.053"]
GEN_DIST_PUBLICSERVICES [pos="-0.090,-0.080"]
LAND_SIZE [pos="-2.302,-0.065"]
PERC_MARRIED [pos="-0.775,-0.027"]
MORTALITY_REL [pos="-1.694,-0.023"]
PERC_FEMALE [pos="-1.256,-0.035"]
PERC_SOCSEC [pos="1.339,-0.063"]
POPULATION [exposure,pos="-2.104,-0.042"]
POP_DENSITY [pos="-1.339,-0.066"]
AVG_AGE -> MORTALITY_REL
AVG_AGE -> POPULATION
AVG_ENERGY_CONS -> CRIME_TOTAL
AVG_HH_SIZE -> AVG_ENERGY_CONS
AVG_HH_SIZE -> AVG_HOUSE_VALUE
AVG_INCOME_CAPITA -> CRIME_TOTAL
AVG_INCOME_CAPITA -> PERC_SOCSEC
AVG_INCOME_CAPITA <-> CAR_PER_HH
BIRTH_REL -> POPULATION
BUSINESS_LOCATIONS -> AVG_HOUSE_VALUE
CAR_PER_HH -> GEN_DIST_PUBLICSERVICES
CAR_PER_HH -> PERC_SOCSEC
EMPTY_HOUSE_PERC -> AVG_ENERGY_CONS
EMPTY_HOUSE_PERC -> AVG_HH_SIZE
EMPTY_HOUSE_PERC -> CRIME_TOTAL
GEN_DIST_PUBLICSERVICES -> CRIME_TOTAL
LAND_SIZE -> POPULATION
LAND_SIZE -> POP_DENSITY
PERC_MARRIED -> CRIME_TOTAL
MORTALITY_REL -> POPULATION
PERC_FEMALE -> CRIME_TOTAL
PERC_SOCSEC -> CRIME_TOTAL
POPULATION -> PERC_FEMALE
POPULATION -> POP_DENSITY
POP_DENSITY -> AVG_HOUSE_VALUE
POP_DENSITY -> BUSINESS_LOCATIONS
POP_DENSITY -> GEN_DIST_PUBLICSERVICES
}
'))
plot(g)

d <- subset(cbsData, select = c(
AVG_AGE,
AVG_ENERGY_CONS,
AVG_HH_SIZE,
AVG_HOUSE_VALUE,
AVG_INCOME_CAPITA,
BIRTH_REL,
BUSINESS_LOCATIONS,
CAR_PER_HH,
CRIME_TOTAL,
EMPTY_HOUSE_PERC,
GEN_DIST_PUBLICSERVICES,
LAND_SIZE,
PERC_MARRIED,
MORTALITY_REL,
PERC_FEMALE,
PERC_SOCSEC,
POPULATION,
POP_DENSITY ) )

localTests(g,d,type = 'cis.chisq')
