# finalDags.R
# file to house the dags for testing
#iter 3
gtemp <- dagitty('dag {
AGE_AVG [pos="0.164,-0.076"]
BUSINESS_REL [pos="-0.268,-0.062"]
CRIME_TOTAL [outcome,pos="-0.044,-0.038"]
DENS_POP [pos="-0.663,-0.078"]
ENERGY_AVG [pos="-1.197,-0.053"]
FEMALE_PCT [pos="0.916,-0.043"]
HH_SIZE [pos="-1.128,-0.063"]
INCOME_LOW40PCT [pos="0.528,-0.067"]
MARRIED_PCT [pos="0.030,-0.055"]
PERC_IMMIGRATION_ORIG [pos="-0.799,-0.043"]
PUB_SERV [pos="-0.524,-0.063"]
SOCSEC_PCT [pos="0.889,-0.051"]
AGE_AVG -> MARRIED_PCT
BUSINESS_REL -> CRIME_TOTAL
BUSINESS_REL -> PUB_SERV
DENS_POP -> BUSINESS_REL
DENS_POP -> HH_SIZE
DENS_POP -> INCOME_LOW40PCT
DENS_POP -> PERC_IMMIGRATION_ORIG
DENS_POP -> PUB_SERV
FEMALE_PCT -> CRIME_TOTAL
FEMALE_PCT -> SOCSEC_PCT
HH_SIZE -> CRIME_TOTAL
HH_SIZE -> ENERGY_AVG
HH_SIZE -> MARRIED_PCT
HH_SIZE -> PUB_SERV
INCOME_LOW40PCT -> CRIME_TOTAL
INCOME_LOW40PCT -> SOCSEC_PCT
MARRIED_PCT -> CRIME_TOTAL
MARRIED_PCT -> SOCSEC_PCT
PERC_IMMIGRATION_ORIG -> CRIME_TOTAL
PERC_IMMIGRATION_ORIG -> ENERGY_AVG
PERC_IMMIGRATION_ORIG <-> PUB_SERV
PUB_SERV -> CRIME_TOTAL
SOCSEC_PCT -> CRIME_TOTAL
SOCSEC_PCT -> PERC_IMMIGRATION_ORIG
FEMALE_PCT -> SOCSEC_PCT
}')
